language: node_js
dist: trusty
node_js: stable

cache:
  bundler: true
  directories:
    - node_modules

addons:
  selenium: latest
  firefox: "51.0" # testem doesn't work with Firefox 52, revisit and set to latest if possible
  apt:
    packages:
      - google-chrome-stable

before_script:
  - gulp

script:
  #- xvfb-run testem ci --reporter dot
  - selenium-standalone install
  - xvfb-run -a selenium-standalone start &
  - sleep 10
  - gemini update
  - ./push.sh

deploy:
  api_key:
    secure: TaF0rF0+n/t3jchds6RSahdIwV+VozFEzGXdnwKzX8TnW2afGU7hh50BJHdQA6/mm0VbgxwAfIDMYU2luLwQn8CJCcJYp7g3+g8xsH15q8ny2AUmIkQQ2sWY43Vk1yMHIwzuAlHy5Pv5qKk8cYRVY5fwaCl/4KfvpIn4F2/DjwU=
  email: limon.monte@gmail.com
  provider: npm

notifications:
  email:
    on_success: never

env:
  global:
    secure: XEMIc26VO9mOvVSPFwNVYGIPeOgMoyvJ0xTrHFuWYeD++ashpi4URQ41bR8LozD9q6JLKP7emLBLt/ExTTKA2C3Z/8bVdC81x//unH6ZxtpQxDIBupXgPvCESiPu16F7CDRrgmOymYoAH9B13C03wjm0eLo8JYq4AMwLTR/TmCo=
