language: node_js
dist: trusty
node_js: stable

cache:
  bundler: true
  directories:
    - node_modules

addons:
  selenium: latest
  firefox: "51.0" # testem doesn't work with Firefox 52, revisit and set to latest if possible
  apt:
    packages:
      - google-chrome-stable

before_script:
  - gulp

script:
  #- xvfb-run testem ci --reporter dot
  - selenium-standalone install
  - xvfb-run -a selenium-standalone start &
  - sleep 10
  - gemini update
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - git add .
  - git status
  - git commit -m "Travis build: ${TRAVIS_BUILD_NUMBER}"
  - branch_name="$(git symbolic-ref HEAD 2>/dev/null)"
  - branch_name=${branch_name##refs/heads/}
  - echo $branch_name
  - git push

deploy:
  api_key:
    secure: TaF0rF0+n/t3jchds6RSahdIwV+VozFEzGXdnwKzX8TnW2afGU7hh50BJHdQA6/mm0VbgxwAfIDMYU2luLwQn8CJCcJYp7g3+g8xsH15q8ny2AUmIkQQ2sWY43Vk1yMHIwzuAlHy5Pv5qKk8cYRVY5fwaCl/4KfvpIn4F2/DjwU=
  email: limon.monte@gmail.com
  provider: npm

notifications:
  email:
    on_success: never
